### ISSUE TITLE
traceback from running the program

### ISSUE THREAD

**Issue by adl212** [gdavid7/sandbox#2]
When the program runs, it says that "Sandbox_v3.py" cannot be found in my system.

**Comment by adl212** [comment]
actually, it says, "Failed to execute script, Sandbox_v3.py"

**Comment by adl212** [comment]
Here's the whole traceback:
```
Traceback (most recent call last):
  File "Sandbox_v3.py", line 71, in <module>
  File "eel\__init__.py", line 134, in start
  File "eel\__init__.py", line 156, in show
  File "eel\browsers.py", line 63, in open
  File "eel\chrome.py", line 12, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[10320] Failed to execute script Sandbox_v3
```

**Comment by gdavid7** [comment]
Hi, can you explain the steps to reproduce this error?

**Comment by adl212** [comment]
So, I opened the exe file in this github and saved the file. Then, when I opened it and ran it, it gave me this traceback. It closed the program really quickly. Thanks for replying so quickly.

**Comment by gdavid7** [comment]
Hi, it looks like no one else is having this error, so it might be a problem with your computer itself. We will open this issue again if any more people are having problems! Thanks for reporting this!

**Comment by gdavid7** [comment]
This may open in the future if more people have this problem.
